### ISSUE TITLE
`SetPointerBuilder` takes 0 generic arguments but 1 generic argument was supplied

### ISSUE THREAD

**Issue by cswinter** [capnproto/capnproto-rust#229]
After upgrading capnp from 0.12 to 0.14.2, I'm getting this compile error in the sources generated by capnp:

```
error[E0107]: this trait takes 0 generic arguments but 1 generic argument was supplied
   --> /home/clemens/src/LocustDB/target/debug/build/locustdb-9dfc73e0c1bcf468/out/storage_format_capnp.rs:102:31
    |
102 |   impl <'a,> ::capnp::traits::SetPointerBuilder<Builder<'a,>> for Reader<'a,>  {
    |                               ^^^^^^^^^^^^^^^^^-------------- help: remove these generics
    |                               |
    |                               expected 0 generic arguments
    |
note: trait defined here, with 0 generic parameters
   --> /home/clemens/.cargo/registry/src/github.com-1ecc6299db9ec823/capnp-0.14.2/src/traits.rs:82:11
    |
82  | pub trait SetPointerBuilder {
    |           ^^^^^^^^^^^^^^^^^
```

**Comment by dwrensha** [comment]
Does it work if you re-generate `storage_format_capnp.rs` from the schema, using the latest `capnpc` crate?

**Comment by cswinter** [comment]
I ran `cargo clean` and it happens in CI as well: https://github.com/cswinter/LocustDB/runs/2982865855?check_suite_focus=true
But maybe something is still getting cached somewhere, I'll try a completely new checkout 🤷

**Comment by dwrensha** [comment]
I see `Compiling capnpc v0.12.4` in that log. You'll need to use `v0.14`.

**Comment by cswinter** [comment]
Oh, I completely forgot there's another separate `capnpc` dependency, guess I should have reread the docs 😄
Thanks for your help!
